# Generated by Django 5.0.2 on 2024-03-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valutes', '0002_currency_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='slug',
            field=models.SlugField(),
        ),
    ]
