# Generated by Django 5.0.2 on 2024-03-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valutesBlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencyarticle',
            old_name='tittle',
            new_name='title',
        ),
        migrations.AddField(
            model_name='currencyarticle',
            name='display_status',
            field=models.CharField(choices=[('CD', 'Можно отобразить'), ('NCD', 'Нельзя отобразить')], default='CD', max_length=3, verbose_name='Статус отображения'),
        ),
    ]
