# Generated by Django 5.0.2 on 2024-04-07 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valutes', '0004_alter_currency_slug'),
        ('valutesBlog', '0002_rename_tittle_currencyarticle_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
            ],
        ),
        migrations.AddField(
            model_name='currencyarticle',
            name='currencies',
            field=models.ManyToManyField(to='valutes.currency', verbose_name='Валюты'),
        ),
        migrations.AddField(
            model_name='currencyarticle',
            name='article_order',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='valutesBlog.articleorder', verbose_name='Тип новости'),
            preserve_default=False,
        ),
    ]
