# Generated by Django 5.0.2 on 2024-04-07 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valutesBlog', '0003_articleorder_currencyarticle_currencies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyarticle',
            name='article_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='valutesBlog.articleorder', verbose_name='Тип новости'),
        ),
    ]
