# Generated by Django 5.0.2 on 2024-04-07 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valutesBlog', '0004_alter_currencyarticle_article_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyarticle',
            name='article_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='valutesBlog.articleorder', verbose_name='Тип новости'),
        ),
    ]
