# Generated by Django 5.0.2 on 2024-04-08 13:09

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valutesBlog', '0005_alter_currencyarticle_article_order'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='articleorder',
            managers=[
                ('displayable_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='currencyarticle',
            name='article_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='valutesBlog.articleorder', verbose_name='Тип новости'),
        ),
    ]
