# Generated by Django 5.0.2 on 2024-04-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valutesBlog', '0006_alter_articleorder_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyarticle',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
