# Generated by Django 5.0.2 on 2024-04-22 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valutesBlog', '0007_currencyarticle_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencyarticle',
            name='anons',
        ),
    ]
