# Generated by Django 5.0.2 on 2024-05-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valutesBlog', '0009_alter_articleorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyarticle',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
    ]
